allowBuilds:
  electron: true
  electron-winstaller: false
  esbuild: true
minimumReleaseAgeExclude:
  - lucide-react@1.52.0
patchedDependencies:
  app-builder-lib@26.15.3: patches/app-builder-lib@26.15.3.patch
